language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- "./gradlew build -s -i"
after_success:
- '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && ./gradlew
  artifactoryPublish -s -i'
env:
  global:
  - secure: YLh2DfIvk6W8ZNRMHoYrXdaiOzyL1wK9iWZlFQ/viPGYvdzYBs0MtFHhyZcfMjXR6W0z/xCTBOPIDhJsMF9i/R2yTos9Vsa0MjoJNXLWrbREgAkPdHOneVws3crNvhcvkEIazf+wI+EmQuN7f9ZJhaivlWEHivpcfpsQU2eLgQisXsgX9YaqDq0Ww2uBzaxtsKZ8gTn57IZyoOB931tpKD9Fy/qjNLDXs1BygdkVc1Ae0nZKI0rQ/X23cK7Sy2pcGj+vUczUdgerRo6l1ssI6u/vGEE3he6XG18xxwtNHpcEX4L7rxfl7rMq/dQ5i9mtuyNw/w8xAa6ePPMcY52PY9/3CxZplyBBptQGoVfomRZh8K8CgJ4fWTj7icia466qwHL4pxSX1aKo+w7YAfs3Z4pDke4pKUV69ykk91v2ruRO0dfxTtR0AskODkTEL2FaRjUezdh6/0PIbgN/ImdijWxR3TDuEtLWJpzrRJI8yU1ok3zO5wgl8Z0K5pTFZBKHeDMmF2EHMajHdJw/xtb9+FuVOpjS85ETQQQgnR4miJPSuSQpPgcKdUnI+UbUIIyTLBu5/zMnlsdP8c328BfEdYtSBLpkCxCxEusPVwTkmyRPq+QgfPZ21t5O6RBBNcT3nIA4LapXQ3kcVtvLgq1QP0nlOF3cA8wR7Oplya+QM7s=
  - secure: i+e94Ty4FohWSpDU/9D40S6ifFC6h7yO911+1V4dMHFBVI0tYbUjaS26pdYU3kG4kM7YdlGu4ZtGwrPS17sKF3ZQTwGZBivB06TeyMah+FvU5yA8195bMn/KQ5qnlmHRdPQtxEGf/G52wyVq9GVjBJI8gZ796G/kzbHJnN+OFttidJ+Ux+TtYn9KLGl7fOpwJ3ebmvUDETol/6dZa59ceGEMketXcReA2Z+vFkiBA3Z5gWZqi9DtVq2HBLfQm7C14J8TBgrc85J5skNvQCC5YEdxJ22fUxGhbFHn2odx0WBsSFsbeVru8yzu0jizL4wjSS0UBf70AakNcwWkJ2Y+JEZszM/A1gCD4Rkjs/IIYoE9jpDCIBkz7PeeeWCKbuwwFyEHbagzSQaUuCil/J+6bRUsk2SkiobbEZTKknQl69vLBCWfyxYH771b1b/rjfW0MvGNWNn1Et32TT7CywBhdt9w2eliFiRntF2xKDVWoA1UOdFc+q5A3+JfN22qHPh5KTTm1A0Nnufa4xZmAX2pbprlt8YHnc5lvJZ9v10x2n0l71FfZd0/WkjrZnFbQvejAA/HFJNf5SYW9LqmtvkIH57kNDaq54A0H7oGZyCs8g2Ee/co2j5MgoEzhjUwkP3lLuyd0CQIJGr+6h2tGcfGhq7NDEXBF7eezVkSajW/ITY=
