language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- "./gradlew build -s -i"
after_success:
- '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && ./gradlew
  artifactoryPublish -s -i'
env:
  global:
  - secure: "gY67nd/cpYaONNPeaGuEeDWfq8VzwgBRVmpZyb0kKMlxhGbry7B3gQG3etjx2h9mED6e8LpqgJdzTdbQ7rUiOqDcwNg7dHEzVGnerYf0i3vk0oU89eJOwLF8Hkz3rMg1IyOZe6Ue+Mg3JCdXVSWQVIqjLb4XD3Hn91rsJXGbNqtmSt53kKwDCdA1aF6KmSTLvqwHTa1s0htNdzcS7oVaYziXq6zq7a+psWGh0QC6D/vIlLBKCOV3denJ7tId3IYZaAL/j5b+aagy7Lcx3tU5sqI5qomDPJMLIjgyfPVv/WkOhzvK1mbxGkKFA1j950+lzw4Fze2D6SpG8PCw+i6GL130rXCVXpNC+ZmWk6hgu26r89IfmWxMLgFQh5nVLDxeXrYVSstHoeKXjwIcZpVId1onNPbFdgwAVoNCJKktRlfTD6eLSeLC/NpfHofKGnefYuKiIKUm7Z0rzKbwC/RAj1C6wg3V3n2WFpSQzm7ow7yz9KWpPAA59VcK4Fi9HbxTKgPvSgf04Rej19RsFRjV2YxNT+PEqA/SRM0RbdWoIU3NT9vfJtzy1iOJyqy7IjzdbkZU4Y95fMM+Jr81bh+c6mQmws73/T5oFcau1lUjjTjtLy7hHUQX8k2Kz7+HyLtio8wI6QA1ArhDt1duWvcSUq6PZOYquelo+SZuK0JF9W8="
  - secure: "YarjIo0whQdfpx7mFDzF7PtiXx5YAY/7obLMLgVQDsjWez1v31ARYRW5IexoU8cNL6AP6FyGVJzBcjtXcyqNWZWb14uPZ2otKcDx0wMehBaXcjcEGZKaOe2LWg+QfU57cNvNymwA9AjRmpGCVqUDBTTBPKrfI3TJcelsHoa64uoaaA20DCzRE/A9MTN45zJlTw11Idj0H5obp1LetfhAl3ge3Mv2oJPRUdUF6gWDkZvfq+lTMotYtTNRaUYxRjdrnJp3gKZ1khdZzM9jtIQH1CxPWtyukp3EzltX1u5wVFDLj5WfvObQ/Caae9LnAf1KOmVqmeHaFnCpjXZ23MaDfiYeCTkoJEGfg+nUrPlfmOb9JL7LnPx2LEtAJBqIuf/JXrTFPGsL+08cPq3rQ+lBECP9BbIqe4VCRwr9ehxJ17B25TGjU/eOQetUU0fI9vQNrBebndO8grU0w8dAWwxqVbjPFAVs3z29woTJ2VE7VTSkPL6ocMuBy3xDZ9uio148J5pmi8OwLXjTQyP4rqYUqnIVV4zFQB0qaemBb3saEnsDflT7RvQ2e3lXqRUHJbZv1fI55IuAsjJ1hUfFF+MKWt1Lgw60b6/I1MjhH+l7ZSlczStBFqQAHEqMSEsFb8x9rXm1kk5XNflZZESRdf5KY0483tGWKeV2qdWLZt06vTQ="

