language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- "./gradlew build -s -i"
after_success:
- '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && ./gradlew
  artifactoryPublish -s -i'
env:
  global:
  - secure: eCvW3yebzjpgOhLwXZ74yV4B0fg/lq41XrBxdyJGWSlootcKHpXhA30gNn0EssQ0jC+i5vb+VCQVhFTREynUwTgJMTLe8SjpPu0SnllUeYjwGeBg5qVOnoa2OedTKWIHfnPG0s17YmpcYgZ6Sw8nGRSgKr/Pcacu748bTG8/InrcdarH+kDLBfZev9lqaPTiFC+HMxckU9jbR9vmf3OPRwTz/GdajEKkA6J58RdHuU4BWQuZpvxIxNjpK72LorgUe+nq4cdtPFicQHau2B+QYB61NEG4hFlsKmspZvn3WmBtqKTJexIXejOISVFV/bcLfSz97Fei5qLsDMB3W5geHJ9HEbjiQgoyqOwEvzKBfbw8iS+1a+AWq5KiI7nv9YWD/CRD1P1ZHZ+DnrxX2XJza3U7l256LntXqXkOisbDqswBb2BsC/Z0OSnYKh7LrkDrhUBD4KvOsqx+i9mBjFSPZ7b8PLagMbiEEZZOhkLGnnZd7yDlhWqz1cJ+fMCyqWolhAaHvXvADHquR4Vy5NywNYZf3+dJYLRJv52qWI3hfpMOj2vKYfbRBBEsYOVrlpkTWXSQ/1YKzx9Uei7XZjxk3QCXmv+/1pyDRsgxG6UxYGF6Fz/Ku53OjCW160l6plbubL+EecSAAEzs6myOTihj6t50NqxVfhcqwntU+LZRZjQ=
  - secure: A1wU4bReuzu54hwROhVQSsLODfJUkQUoTSl81SWsLRdpnfRMkFP+lrx+2GsWMU6w50F+7oaMDvAccvdsjDIANXA6ToNTxlTZ1CRLx26+XTO2+pZ7xn/eQvrUzZg0kcvHKThTdYBwuG9jfeoNpWhpVxOJeHsDiRq65/do7kK6CI/wvq9Y037lnSs4bYwMvcvuwPcV97rAi6SjVba1xfVD2hEDZoBEQwBIi76+P0JYGlcF9HN/sMZzqFkPDf6DBBbpEHSknwU99RSnmIuWuk6RwjCFvpSPG7SyMuvPsyeSfwzgZ+illVmEAZNL01e9nGuxTzfNzeg3r1zu50BpXkt5sbgzpZW8DNUi66wmx3r3l4h81FaRhW+eAMN6zebbmLIAcfCNMXNaTe+XcFCS+kThT1IkkMLw68Z2S930PtaHhzufuP3SFXv/mP+wXf5Sy0u0ud9Ap1ZYhcUC1+/MGKYfv8XhVftQVNRb9otC8RvXb8WV3rVKld8CSESnxPIyqPl6BPbJzXQ5vQDZNFIyZOyF+BUtktyef/6Mw1ycZNgeEuxMQZGAWa9HxZjNbo+bXdTjOZRyrXPF0QeuCMFoY5ZqsELX2MWxtL2ZXnOt/Qex8nVj2WzKwU/UfkQ2SxHT012ekK/hKLJMjD49Eno/KPuLs/ZF+4vRJviLKhrZsgC2aqs=
